### ISSUE TITLE
unclear if both renaming and hiding can be used at once

### ISSUE THREAD

**Issue by pascalpoizat** [pascalpoizat/vbpmn#15]
It is unclear whether both renaming and hiding can be used at once. I think that the python script enables it (still, to be verified). If the web app makes it possible then the presentation of the hiding and renaming sub-options/parameters should be done at once.
Solution: develop an example where both renaming and hiding are required to yield conservative evolution and see if it works.

**Comment by ajaykrishna** [comment]
Fixed along with 7c50ba3f5328a9f56f644af4fc836cd127aa4d30
