### ISSUE TITLE
Update gh-pages wrt the new version of the war

### ISSUE THREAD

**Issue by pascalpoizat** [pascalpoizat/vbpmn#19]

**Comment by ajaykrishna** [comment]
Updated VBPMN to version 1.1 818c1d3de98237f98d4b6271f28632ebf4cf20e9

**Comment by pascalpoizat** [comment]
closed by https://github.com/pascalpoizat/vbpmn-web/commit/818c1d3de98237f98d4b6271f28632ebf4cf20e9
