### ISSUE TITLE
inconsistency in README files in the master and gh-pages branches

### ISSUE THREAD

**Issue by pascalpoizat** [pascalpoizat/vbpmn#7]
The information in the readme files of the two branches is not the same.
Solution: unify.

**Comment by ajaykrishna** [comment]
@pascalpoizat As we have only the webpages hosted here, should I replace the [README.md](https://github.com/pascalpoizat/vbpmn/blob/master/README.md) in the `master` branch with the [README.md](https://github.com/pascalpoizat/vbpmn/blob/gh-pages/README.md) from the `gh-pages` branch?

**Comment by pascalpoizat** [comment]
@ajaykrishna I think the README is more often a description of the tool / installation guide / usage guide. Therefore I would make it minimal with this information :
- describe the tool (minimal since we have the Web pages)
- link to the Web pages
- list the contributors (all, including you)
- give the licence badge (I like what you did with it)

And then copy it in master, gh-pages, origin/master, origin/gh-pages, gh/master, and gh/gh-pages.
